### ISSUE TITLE
Windows 10 Error : UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3322: character maps to <undefined>

### ISSUE THREAD

**Issue by gsarosi67** [gaogaotiantian/watchpoints#2]
When running on Windows 10 watchpoint crashes with an exception and the following error message:

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3322: character maps to <undefined>

The problem is the open of the source code file in write_print.py on line 53:

    `with open(exec_info[1]) as f:`

The encoding needs to be specified in the open call as below:

   ` with open(exec_info[1],"r",encoding='utf-8') as f:`

**Comment by gaogaotiantian** [comment]
Thanks for finding this. Fixed in #3 and released as 0.1.3
