### ISSUE TITLE
Intention of the `all` variable in `watchpoints/__init__.py`

### ISSUE THREAD

**Issue by bzoracler** [gaogaotiantian/watchpoints#38]
Thanks for this black-magic library!

I'm currently trying to get a set of typing stubs added to typeshed (https://github.com/python/typeshed/pull/13248). One thing that came up was the intention of `all`:

https://github.com/gaogaotiantian/watchpoints/blob/934d7a36633487b38d18c8348176c29b6e3c4b9a/src/watchpoints/__init__.py#L11-L14

Was this intended to be `__all__`, for controlling the symbols imported with `from watchpoints import *`?

**Comment by gaogaotiantian** [comment]
Yes, that was a typo. If you want, feel free to make a PR to fix :) Otherwise I can fix it when I get some time.
