### ISSUE TITLE
Need conditional expressions

### ISSUE THREAD

**Issue by rswgnu** [gaogaotiantian/watchpoints#4]
Great idea, as are all of your repos.

This really needs the ability to limit prints to only when certain boolean expressions are true that utilize the watchpoint variable.  Otherwise, the logs could get too big too fast.  Are conditional expressions already in there?

**Comment by gaogaotiantian** [comment]
The tricky part of conditional expression is that the conditional check could potentially be in any scope, and you really do not have control of what variable you can have access to. I would definitely think about whether it's possible to add intuitive conditional check in watchpoints. However, at this point, you could always implement your own callback function, where you can basically do anything you want with the observing object.
