### ISSUE TITLE
ENH : __eq__ operator when a pandas.DataFrame is involved

### ISSUE THREAD

**Issue by KikeM** [gaogaotiantian/watchpoints#5]
Hi!

First of all, I would like to thank you. This is an incredibly useful project. 

Now, when I was attempting to use it on my code I have runned into an interesting problem: when `watch` is applied to a `pandas.DataFrame`, the `__eq__` operator returns the comparison _element-wise_.

Thus, the code cannot correctly asses if both elements are equal, since there is a reduction step missing to tell if all elements are equal or not.

Any ideas on how I could go around this issue?

**Comment by gaogaotiantian** [comment]
Hi,

Sorry I did not quite understand your question, probably because I'm not familiar with pandas at all(not a data scientist lol). The concept *element* is not clear to me and it seems a bit weird to do a reduction first before comparing. 

Could you maybe give me a very simple example of what's not working?

For customized data structures, there are two tricky parts: copy and compare. Now ``watchpoints`` provide shallow and deepcopy, and different compare schemes. However, maybe it would work better for you(and other people) if you can custom your own copy and compare function?

**Comment by gaogaotiantian** [comment]
I added custom copy and compare feature on #6 and it is released with 0.1.4. Please let me know if that helps this issue.

**Comment by KikeM** [comment]
Hi!

Yes, the change in `0.1.4` is what I need.

I have used it, but now the code is failing in the following line:

```python
  56         def changed(self, frame):
  57             """
  58             :return (changed, exist):
  59             """
  60             if "variable" in self.track:
  61                 if frame is self.frame and self.localvar is not None:
  62                     if self.localvar in frame.f_locals:
  63  ->                     if frame.f_locals[self.localvar] != self.obj:
```

Shouldn't the adhoc comparison function `cmp` be used here too, if provided?

**Comment by KikeM** [comment]
Please find here a MWE. 

```python
import pandas as pd
from watchpoints import watch

watch.config(pdb=True)

df = pd.DataFrame(
    data=[[1, 2], [3, 4], [5, 6]], index=list("abc"), columns=list("AB")
)


def __comparison_dataframe__(obj1, obj2):
    return not obj1.equals(obj2)


watch(df, cmp=__comparison_dataframe__)

# Other stuff happens
a = 2
b = a + 5

# Should watch here
df.loc["a", "B"] = 10
```

The traceback is:

```python
Traceback (most recent call last):
  File "mwe.py", line 18, in <module>
    a = 2
  File "mwe.py", line 18, in <module>
    a = 2
  File "D:\envs\XXX\lib\site-packages\watchpoints\watch.py", line 121, in tracefunc
    changed, exist = elem.changed(frame)
  File "D:\envs\XXX\lib\site-packages\watchpoints\watch_element.py", line 63, in changed
    if frame.f_locals[self.localvar] != self.obj:
  File "D:\envs\XXX\lib\site-packages\pandas\core\generic.py", line 1329, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

As you can see, I get passed the comparison step, but not this one here.

**Comment by KikeM** [comment]
Sorry, I did not answer to your question about _element_.

`pandas.DataFrames` are numpy arrays (matrices) with a nice wrapping. Therefore, some operations are defined _element-wise_, that is, for each entry of the matrix. 

This is what happens with the `__eq__` method, instead of returning a bool, it returns a bool _per matrix entry_. And that is why a `ValueError` is raised, demanding the use of a reduction method such as `any` or `all`. From a matrix of booleans, Python cannot tell if the equality conclusion is True or False. 

As you can see, in my MWE I have used the [equality method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html#:~:text=equals,-DataFrame.&text=Test%20whether%20two%20objects%20contain,the%20same%20shape%20and%20elements.) `equals`, which does return a bool :)

**Comment by gaogaotiantian** [comment]
Okay I get what you mean. I'll fix this today. However I'll go another approach. I thought about this situation and I believe that it would be better to use ```is not``` instead of ```!=``` in ```"variable"``` compare. For ``"object"`` compare, the program will still honor the customized compare function.

**Comment by KikeM** [comment]
Oh great!

Many thanks, I will try out tomorrow morning and let you know how it went ;)

**Comment by gaogaotiantian** [comment]
This feature is released as 0.1.5.

**Comment by gaogaotiantian** [comment]
Hi @KikeM, I never heard from you again. Is the release work as you expected?

**Comment by KikeM** [comment]
Hi! 

Yes, it did work. We can close this issue, thank you :) 

The reason I didn't close it immediately is that it worked in a different way than I expected.
However, we can discuss that in another issue, since generalization has been achieved and therefore this issue solved. 

I will open the other one in the coming days once I wrap my head around the way you expect this to work.

Good work 👍
